### ISSUE TITLE
The security of client in gotham-city

### ISSUE THREAD

**Issue by zytMatrix** [ZenGo-X/gotham-city#65]
I think there has a security problem according to the logic of gotham-city. The private key x2 of client and a common public share "master key" are saved on the client side. If the attacker gets the data of the client, can the private key of the wallet be calculated according to Q and x2?

**Comment by leontiadZen** [comment]
Thanks for taking time exploring the repo.
Thanks to Diffie–Hellman problem , working under appropriate groups, an adversary obtaining x2 and having Q such that x1.x2=Q (in the appropriate group) cannot get x1, unless it knows x1 already

**Comment by leontiadZen** [comment]
not an issue
